site_name: Abdotonomous
repo_url: https://github.com/Das-Auto/abdotonomous-docsi
nav:
    
    - 🚗 Home: index.md
    - Technical Docs:
        - 'Features':
            - 'TTC Feature': readmes/ttc.md
            - 'Kalman Filter': readmes/kalman_filter.md
            - 'Lidar Obstacle Detection': readmes/lidar_obstacle_detection.md
            - 'GPS': readmes/gps.md
theme:
  logo: assets/wheel_logo.svg
  favicon: assets/wheel_logo_black.svg
  icon:
    logo: bootstrap/envelope-paper
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    # - navigation.expand
    - navigation.sections
    - navigation.footer # next and previous buttons
    # - navigation.sections
    # - toc.integrate
    # - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
    # - toc.follow
    - toc:
      permalink: true
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-on-10
        name: Switch to dark mode
      primary: primary
      accent: pink
    - scheme: slate
      toggle:
          icon: material/lightbulb-on
          name: Switch to light mode
      primary: teal
      secondary: lime
      accent: yellow
    
extra:
    social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/hagar-usama
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/hagar-usama/
  
    version:
      provider: mike
      analytics: 
    
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
 
 
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      title: "➤ Table of Contents"



copyright: |
  &copy; 2023 Hagar Usama